########################################################################################################################
### lệnh và quyền
########################################################################################################################
# +------------------+---------------------------------------------------------+-----------------------------+
# |      lệnh        |                      Mô tả                              |       Quyền                 |
# +------------------+---------------------------------------------------------+-----------------------------+
# | /rlc             | Hiển thị trợ giúp                                       | randomlootchest.general     |
# | /rlc additem     | Mở GUI thêm vật phẩm                                    | randomlootchest.additem     |
# | /rlc addchest    | Thêm rương cố định bằng cách nhấn chuột phải            | randomlootchest.fixedchest  |
# | /rlc delchest    | Xóa rương cố định bằng cách nhấn chuột phải             | randomlootchest.fixedchest  |
# | /rlc delall      | Xóa tất cả rương cố định                                | randomlootchest.delall      |
# | /rlc killall     | Xóa tất cả rương ngẫu nhiên khỏi máy chủ                | randomlootchest.killall     |
# | /rlc togglebreak | Cho phép phá rương ngẫu nhiên                           | randomlootchest.togglebreak |
# | /rlc forcespawn  | Tạo rương ngẫu nhiên ngay lập tức                       | randomlootchest.forcespawn  |
# | /rlc rndtime     | Ngẫu nhiên hóa thời gian tồn tại của rương              | randomlootchest.rndtime     |
# +------------------+---------------------------------------------------------+-----------------------------+
########################################################################################################################

########################################################################################################################
### Tùy chọn chung
########################################################################################################################
# Thế giới xuất hiện rương (cả ngẫu nhiên và cố định)
World: "world"

########################################################################################################################
### rương vị trí ngẫu nhiên
########################################################################################################################
# Khu vực rương xuất hiện
LargestDinctance_X: 10
SmallestDinctance_X: -10
LargestDinctance_Y: 255
SmallestDinctance_Y: 0
LargestDinctance_Z: 10
SmallestDinctance_Z: -10
# Thời gian chờ giữa các lần tạo rương (giây)
SpawnChestPerTime: 10
# Bật/tắt xóa rương tự động
KillChest: true
# Thời gian trước khi rương biến mất (giây)
KillChestAfterTime: 60
# Thông báo khi không được phép phá rương
NotAbleToBreakAchest: "&cBạn không thể phá rương loot!"
# Để trống để tắt thông báo
MessageOnSpawn: "&6&l--------------------------------------\n&crương đã xuất hiện tại &ax: &6{X} &ay: &6{Y} &az: &6{Z}.\n&6&l--------------------------------------"
# Để trống để tắt thông báo
MessageOnLoot: "&6&l--------------------------------------\n&4{Player} &cđã loot rương tại &ax: &6{X} &ay: &6{Y} &az: &6{Z}.\n&6&l--------------------------------------"
# Để trống để tắt thông báo
MessageOnKill: "&6&l--------------------------------------\n&4rương tại &ax: &6{X} &ay: &6{Y} &az: &6{Z} &4đã biến mất!\n&6&l--------------------------------------"
# lệnh thực thi khi người chơi mở rương
CommandsToExecuteOnLoot:
  - eco give {player} 100
# Hiệu ứng rương khi hoạt động
RandomChestEffect: MOBSPAWNER_FLAMES
# Âm thanh khi rương xuất hiện
RandomChestSound: NONE
# Âm thanh khi mở rương
RandomChestOpenSound: CHEST_OPEN|BLOCK_CHEST_OPEN

########################################################################################################################
### Điều kiện xuất hiện rương. CẢNH BÁO! THAY ĐỔI CÓ THỂ GÂY LỖI
########################################################################################################################
# Có ba điều kiện phải đồng thời thỏa mãn:
# SpawnBlockCondition - Điều kiện khối bị rương thay thế
# UnderBlockCondition - Điều kiện khối bên dưới
# SideBlockCondition - Điều kiện khối xung quanh
#
# Điều kiện kiểm tra vật liệu khối. Mỗi điều kiện là chuỗi chứa tên vật liệu và/hoặc thuộc tính.
# Sử dụng ' ', ',', ';' để phân cách nhiều tham số
#
# Tham số chia hai nhóm: tích cực (phải có) và tiêu cực (không được có)
# Sử dụng '!' để đánh dấu điều kiện tiêu cực
#
# Có thể sử dụng thuộc tính vật liệu:
# _FUEL_, _RECORD_, _OCCLUDING_, _TRANSPARENT_, _BLOCK_, _BURNABLE_, _EDIBLE_, _FLAMMABLE_, _SOLID_, _GRAVITY_
#
# Ví dụ: "!RAILS, _TRANSPARENT_, !SAPLING" nghĩa là:
# "Vật liệu phải trong suốt và không phải đường ray hoặc cây non"
########################################################################################################################
# Điều kiện khối bị thay thế
SpawnBlockCondition: "AIR,SNOW,CARPET"
# Điều kiện khối bên dưới
UnderBlockCondition: "!_TRANSPARENT_,!WATER,!STATIONARY_WATER,!LAVA,!STATIONARY_LAVA,!SOIL,!GRASS_PATH"
# Điều kiện khối xung quanh
SideBlockCondition: "!CACTUS"

########################################################################################################################
### rương vị trí cố định
########################################################################################################################
# Khoảng thời gian cập nhật inventory (ngẫu nhiên giữa Min/Max, giây)
FixedChestUpdateTimeMin: 10
FixedChestUpdateTimeMax: 20
# Hiệu ứng khi rương cập nhật
FixedChestEffect: EXPLOSION
# Âm thanh khi rương cập nhật
FixedChestSound: DIG_GRASS|BLOCK_GRASS_BREAK

########################################################################################################################
### Giao diện kho đồ (GUI)
########################################################################################################################
Inventory_Name: "&cChúc mừng!"
Inventory_Slots: 27
ItemAmountToAdd: 5
NotificationInterval: 300 # Thời gian chống spam (giây)
########################################################################################################################
### Giá trị Hiệu ứng và Âm thanh
########################################################################################################################
# Sử dụng NONE để tắt hiệu ứng/âm thanh
#
# Tên hiệu ứng hợp lệ:
#   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
# Tên particle (spigot 1.9+):
#   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#
# Tên âm thanh hợp lệ:
#   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#
# Có thể chỉ định nhiều giá trị cách nhau bằng '|', ' ', ',', ';'
# Plugin sẽ dùng giá trị đầu tiên khả dụng
########################################################################################################################

########################################################################################################################
### Bật plugin sau khi cấu hình hoàn tất
########################################################################################################################
EnablePlugin: false